### PR TITLE
Update reporting section

### LINKED ISSUE #8: Suggestion: San Jose 311 App Download Link
I find it more useful to have the app. A quick link to download via iphone or android would be useful. 
iphone: https://apps.apple.com/us/app/my-san-jose-a-newway/id1231429879
android: https://play.google.com/store/apps/details?id=com.astcorporation.three11&hl=en

### PR DESCRIPTION
**Pull request by brianpham**
- Add matrix table to easily know who and where to report issues
- Add direct link to iOS and Android apps

Closes #8 #11

### CODE REVIEW

**Comment by brianpham** [comment]
Screen Shot 2020-07-23 at 2 32 47 PM

@bringhurst I need some help with the padding issue for the table. Was taking a look at the config.yaml, but didn't see anything that might be able to fix that without touching the submodule?

**Comment by bringhurst** [comment]
Will take a look at this later tonight. :)

**Comment by bringhurst** [comment]
I think it might need a bit more tweaking, but I created a PR for a table shortcode over in #17 -- should be useful for formatting this better.

**Comment by bringhurst** [comment]
Going to merge this in, then submit another PR for the formatting. TY!

**Pull request merged**
